/*
 * answerVerifier.ts — Cross-references generated answers against source chunks.
 *
 * PURPOSE: Implements a token-overlap claim verification engine to detect
 * hallucination risks in RAG answers offline on the mobile client.
 *
 * DESIGN DECISIONS:
 * - Pure TypeScript/JavaScript client-side execution (zero lag).
 * - Extracts sentences (claims) and tokenizes them using retrievalService's tokenizer.
 * - Measures token overlap against the source context chunks to determine if claims
 *   are grounded in the provided document context.
 * - A claim is verified if it has a token overlap ratio >= 0.35 with any source chunk.
 * - Overall confidence is the fraction of claims that are verified.
 * - Returns a warning string if confidence is below 0.5.
 */

import { tokenize } from './retrievalService';

export interface VerificationResult {
  confidence: number;
  unverifiedClaims: string[];
  warning?: string;
}

/**
 * splitSentences - Segments text into sentences while ignoring periods within
 * common abbreviations (like Rs., Sec., Ltd.).
 */
export const splitSentences = (text: string): string[] => {
  const abbreviations = [
    { pattern: /\bRs\./gi, placeholder: '___RS___', original: 'Rs.' },
    { pattern: /\bSec\./gi, placeholder: '___SEC___', original: 'Sec.' },
    { pattern: /\bNo\./gi, placeholder: '___NO___', original: 'No.' },
    { pattern: /\bCo\./gi, placeholder: '___CO___', original: 'Co.' },
    { pattern: /\bLtd\./gi, placeholder: '___LTD___', original: 'Ltd.' },
    { pattern: /\bInc\./gi, placeholder: '___INC___', original: 'Inc.' },
    { pattern: /\bArt\./gi, placeholder: '___ART___', original: 'Art.' },
    { pattern: /\bvs\./gi, placeholder: '___VS___', original: 'vs.' },
    { pattern: /\be\.g\./gi, placeholder: '___EG___', original: 'e.g.' },
    { pattern: /\bi\.e\./gi, placeholder: '___IE___', original: 'i.e.' },
  ];

  let processed = text;
  for (const abb of abbreviations) {
    processed = processed.replace(abb.pattern, abb.placeholder);
  }

  const rawSentences = processed.split(/[.!?]\s+/);

  return rawSentences
    .map(s => {
      let restored = s.trim();
      for (const abb of abbreviations) {
        restored = restored.replace(new RegExp(abb.placeholder, 'g'), abb.original);
      }
      return restored;
    })
    .filter(s => s.length > 0);
};

/**
 * verifyAnswer - Verifies an AI answer against retrieved source chunks.
 * 
 * @param answer - The text response generated by the LLM.
 * @param sourceChunks - The retrieved document chunks used as context.
 * @returns VerificationResult with confidence score and unverified claims list.
 */
export const verifyAnswer = (
  answer: string,
  sourceChunks: string[]
): VerificationResult => {
  /* Edge case: empty answer */
  if (!answer.trim()) {
    return { confidence: 1.0, unverifiedClaims: [] };
  }

  /* Edge case: no source chunks. In general conversation, we don't have
     grounding sources, so we default to 1.0 confidence to avoid false warnings. */
  if (!sourceChunks || sourceChunks.length === 0) {
    return { confidence: 1.0, unverifiedClaims: [] };
  }

  /* 1. Segment the answer into claims (individual sentences) */
  const sentences = splitSentences(answer);
  const claims = sentences
    .map(s => s.trim())
    .filter(s => {
      /* Skip extremely short sentences or phrases */
      if (s.length < 10) return false;

      /* Skip meta-disclaimers or negative response indicators */
      const lower = s.toLowerCase();
      if (
        lower.startsWith('not found') ||
        lower.includes('not mentioned') ||
        lower.includes('disclaimer') ||
        lower.includes('informational purposes only') ||
        lower.includes('legal advice')
      ) {
        return false;
      }
      return true;
    });

  /* If all sentences are ignored (disclaimers/negative responses), it is verified */
  if (claims.length === 0) {
    return { confidence: 1.0, unverifiedClaims: [] };
  }

  /* 2. Tokenize and extract numbers from source chunks once for faster lookup */
  const chunkTokenSets = sourceChunks.map(chunk => new Set(tokenize(chunk)));
  const chunkNumerics: string[][] = sourceChunks.map(chunk => chunk.match(/\d+/g) || ([] as string[]));

  const unverifiedClaims: string[] = [];
  let verifiedCount = 0;

  /* 3. Evaluate each claim */
  for (const claim of claims) {
    const claimTokens = tokenize(claim);

    /* If the sentence has no content tokens (e.g., all stop words), skip it */
    if (claimTokens.length === 0) {
      verifiedCount++;
      continue;
    }

    let maxOverlapRatio = 0;

    /* Extract all numbers from the raw claim string to bypass tokenizer length limits */
    const claimNumerics: string[] = claim.match(/\d+/g) || ([] as string[]);

    for (let i = 0; i < chunkTokenSets.length; i++) {
      const chunkSet = chunkTokenSets[i];
      const chunkNums = chunkNumerics[i];
      if (chunkSet.size === 0) continue;

      /* Grounding check: Any numeric values in the claim must exist in the source chunk.
         If a number is hallucinated (e.g. Rs 40,000 instead of Rs 25,000), we discard the chunk match. */
      const hasNumericMatch = claimNumerics.every(num => chunkNums.includes(num));

      if (!hasNumericMatch) {
        continue; // Number mismatch, skip this chunk
      }

      let overlapCount = 0;
      for (const token of claimTokens) {
        if (chunkSet.has(token)) {
          overlapCount++;
        }
      }

      const ratio = overlapCount / claimTokens.length;
      if (ratio > maxOverlapRatio) {
        maxOverlapRatio = ratio;
      }
    }

    /* Threshold 0.35 is selected to allow matching even with synonym variances
       or grammatical tense changes (e.g. commences vs commencing). */
    if (maxOverlapRatio >= 0.35) {
      verifiedCount++;
    } else {
      unverifiedClaims.push(claim);
    }
  }

  const confidence = verifiedCount / claims.length;
  const warning = confidence < 0.5
    ? '⚠ Unable to fully verify answer from uploaded documents'
    : undefined;

  return {
    confidence,
    unverifiedClaims,
    warning,
  };
};
